
[[group]]
[[page]]
title = "Hướng dẫn TOML"
desc = "Liệt kê chi tiết các code và giải thích"
icon = "🔥"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-html.html"
[[page]]
title = "Trình tạo mã TOML"
desc = "Giúp bạn tạo mã toml nhanh hơn"
icon = "🔥"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-generator.html"
