
[[group]]
[[page]]
title = "Hướng dẫn TOML"
desc = "Liệt kê chi tiết các code và giải thích"
icon = "🔥"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-html.html"
[[page]]
title = "Trình tạo mã TOML"
desc = "Giúp bạn tạo mã toml nhanh hơn"
icon = "🔥"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-generator.html"

[[group]]
[[editor]]
title = "Chỉnh sửa TOML"
desc = "Sửa trực tiếp code khu vực test"
icon = "⚙️"
file = "test.toml"
placeholder = "[[toml]]"
value = """
[[group]]
[[switch]]
title = "Test switch"
get = "glog test_log_nut"
set = "slog test_log_nut $state"
"""

[[group]]
[[page]]
title = "Kiểm thử mã TOML"
config = "test.toml"
lock-sh = """
[ -f $ETC/toml/test.toml ] && echo 0 || echo "Mở kiểm thử mã TOML trước"
"""