[[toml]]
load-key-sh = "langpath"

[[group]]
[[text]]
rows-sh = '''
cat << EOF
[[rows]]
size = 13
text = "@root_text: {${ROOT^}}(#0dbda2)"
bold = true
icon = "{ICON}/1shield.png"
line-height = 1.3
break = true
markdown = true

[[rows]]
text = "@device_text: {${ANDROID_BRAND} - ${ANDROID_DEVICE}}(#0dbda2)"
break = true
size = 13
bold = true
line-height = 1.3
icon = "{ICON}/1smart.png"
markdown = true

[[rows]]
text = "@operating_system: {Android ${ANDROID_RELEASE} - ${API}}(#0dbda2)"
break = true
size = 13
bold = true
line-height = 1.3
icon = "{ICON}/1android.png"
markdown = true

[[rows]]
text = "@microprocessors: {${CPU_ABI^}}(#0dbda2)"
break = true
size = 13
bold = true
line-height = 1.3
icon = "{ICON}/1cpu.png"
markdown = true
EOF
'''

[[group]]
[[page]]
title = "@editor_rom"
desc = "@setting_text_4"
icon = "{ICON}/project.png"
config = "{HOME}/etc/toml/project.toml"

[[group]]
[[page]]
title = "@customize_text"
desc = "@home_text_2"
icon = "{ICON}/utilities.png"
config-sh = "$ETC/tool-tree.bash Utilities"

[[group]]
[[page]]
title = "@tools_text"
desc = "@home_text_3"
icon = "{ICON}/tools.png"
config = "{HOME}/etc/toml/root.toml"

[[group]]
[[page]]
title = "@plugin_text"
desc = "@home_text_4"
icon = "{ICON}/addon.png"
process = true
config-sh = "$ETC/tool-tree.bash Addon $AON"
