
[[toml]]
load-key-sh = "langpath"

[[group]]
[[menu]]
[[menu.items]]
title = "@guide_title"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-html.html"
[[menu.items]]
title = "@gen_title"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-generator.html"

[[group]]
[[action]]
title = "@project_addon_title"
menu = true
show = true
reload = true
shell = "hidden"
warn = "@project_addon_warn"
script = """
slog id_add_on "$id_add_on"
slog account_add_on "$account_add_on"
mkdir -p "$UZZ/$id_add_on"
"""

[[action.params]]
name = "account_add_on"
title = "@secret_code_title"
desc = "@secret_code_desc"
type = "password"
required = true
placeholder = "Kakathic_test_1234"

[[action.params]]
name = "id_add_on"
desc = "@list_addon_desc"
label = "@input_name_label"
type = "single-select"
options-sh = "findfile for $UZZ"
required = true
editable = true
placeholder = "test_addon"

[[group]]
[[action]]
title = "@create_addon_title"
reload = true
script = """
slog addon_type_toml "$addon_type_toml"
[ "$addon_root" == 1 ] && addon_root_bl=true || addon_root_bl=false
[ -f "$addon_icon_path" ] && cp -rf "$addon_icon_path" "$UZZ/$addon_name_id/icon.png"
if [ -f "$UZZ/$addon_name_id/Add-on.bash" ]; then
sed -i \
  -e "s/^name=.*/name=\"$addon_name\"/" \
  -e "s/^author=.*/author=\"$addon_author\"/" \
  -e "s/^version=.*/version=\"$addon_version\"/" \
  -e "s/^description=.*/description=\"$addon_descss\"/" \
  -e "s/^versionCode=.*/versionCode=\"$addon_code_version\"/" \
  -e "s/^root=.*/root=\"$addon_root_bl\"/" "$UZZ/$addon_name_id/Add-on.bash"
else
echo "# Add-on
id=$addon_name_id
name=\"$addon_name\"
author=\"$addon_author\"
version=\"$addon_version\"
description=\"$addon_descss\"
versionCode=\"$addon_code_version\"
root=\"$addon_root_bl\"" > "$UZZ/$addon_name_id/Add-on.bash"
fi
"""

[[action.params]]
name = "addon_name_id"
label = "@addon_id_label"
desc = "@addon_id_desc"
value-sh = "glog id_add_on"
type = "text"
readonly = true

[[action.params]]
name = "addon_name"
label = "@addon_name_label"
type = "text"
required = true
placeholder = "Test"

[[action.params]]
name = "addon_author"
label = "@addon_author_label"
type = "text"
required = true
placeholder = "Kakathic"

[[action.params]]
name = "addon_descss"
label = "@addon_desc_label"
type = "text"
required = true
placeholder = "Test zzz"

[[action.params]]
name = "addon_version"
label = "@addon_version_label"
type = "number"
required = true
placeholder = "1.0"

[[action.params]]
name = "addon_code_version"
label = "@addon_code_version_label"
type = "number"
required = true
placeholder = 100

[[action.params]]
name = "addon_root"
label = "@addon_root_label"
desc = "@addon_root_desc"
type = "switch"
required = true

[[action.params]]
name = "addon_type_toml"
label = "@addon_type_index"
type = "single-select"
items = ["toml", "bash"]

[[action.params]]
name = "addon_icon_path"
label = "Icon add-on"
type = "file"
suffix = "png"

[[editor]]
title = "@edit_index_title"
run = false
file-sh = """
echo "$UZZ/$(glog id_add_on)/index.$(glog addon_type_toml toml)"
"""
placeholder = """# toml
[[toml]]
[[group]]
title = "Hello"

# bash
home (){
  echo '
  [[toml]]
  [[group]]
  title = "Hello"
  '
}
"""

[[group]]
[[page]]
title = "@manage_addon_title"
icon = "add_online.png"
process = true
config-sh = "$ETC/tool-tree.bash Addon $UZZ"
