
[[toml]]
load-key-sh = "langpath"

[[group]]
[[menu]]
[[menu.items]]
title = "@guide_title"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-html.html"
[[menu.items]]
title = "@gen_title"
link = "https://kakathic.github.io/Tool-Tree/website/Toml-generator.html"

[[group]]
[[action]]
title = "@project_addon_title"
menu = true
show = true
shell = "hidden"
warn = "@project_addon_warn"

[[action.params]]
name = "account_add_on"
title = "@secret_code_title"
desc = "@secret_code_desc"
type = "text"
required = true
placeholder = "Kakathic_test_1234"

[[action.params]]
name = "list_add_on"
desc = "@list_addon_desc"
label = "@input_name_label"
type = "single-select"
options-sh = "findfile for $UZZ"
required = true
editable = true
placeholder = "test_addon"

[[group]]
[[action]]
title = "@create_addon_title"

[[action.params]]
name = "addon_name_id"
label = "@addon_id_label"
desc = "@addon_id_desc"
type = "text"
readonly = true

[[action.params]]
name = "addon_name"
label = "@addon_name_label"
type = "text"
required = true
placeholder = "Test"

[[action.params]]
name = "addon_author"
label = "@addon_author_label"
type = "text"
required = true
placeholder = "Kakathic"

[[action.params]]
name = "addon_descss"
label = "@addon_desc_label"
type = "text"
required = true
placeholder = "Test zzz"

[[action.params]]
name = "addon_version"
label = "@addon_version_label"
type = "number"
required = true
placeholder = "1.0"

[[action.params]]
name = "addon_code_version"
label = "@addon_code_version_label"
type = "number"
required = true
placeholder = 100

[[action.params]]
name = "addon_root"
label = "@addon_root_label"
desc = "@addon_root_desc"
type = "switch"
required = true

[[editor]]
title = "@edit_index_title"
file = "test.toml"

[[group]]
[[page]]
title = "@manage_addon_title"
icon = "add_online.png"
process = true
config-sh = "$ETC/tool-tree.bash Addon $UZZ"
