[[toml]]
load-key-sh = "langpath"

[[group]]
[[menu]]
[[menu.items]]
type = "refresh"
title = "@refresh_text"

[[group]]
[[action]]
shell = "hidden"
reload = true
icon = "{ICON}/folder_rom.png"
title = "@folder_text"
desc-sh = 'echo "@path_text: $SDC"'
script = '''
  if [ ! -d "$FOLDER" ]; then
  slog SDC "$FOLDER"
  mkdir -p "$FOLDER"
  fi
'''

[[action.params]]
name = "FOLDER"
label = "@folder_text"
desc = "@config_text_2"
value-sh = "glog SDC"
type = "folder"
required = true

[[group]]
[[action]]
title = "@project_text_3"
icon = "{ICON}/cleanup.png"
warn = "@project_text_4"
auto-off = true
script = '''
  for vl in $dels; do
  echo "Deleting the folder: $vl"
  rm -fr "$vl"
  done
'''

  [[action.params]]
  name = "dels"
  label = "@option_text"
  options-sh = "findfile folders $SDH/$PTSH"
  multiple = true

[[group]]
[[action]]
title = "@customize_tools_text"
icon = "{ICON}/list_tool.png"
shell = "hidden"
reload = true
script = '''
  slog un_tool_ext4 "$un_tool_ext4"
  slog un_tool_erofs "$un_tool_erofs"
  slog un_tool_f2fs "$un_tool_f2fs"
  slog re_tool_ext4 "$re_tool_ext4"
  slog re_tool_erofs "$re_tool_erofs"
  slog re_tool_f2fs "$re_tool_f2fs"
'''

  [[action.params]]
  name = "un_tool_ext4"
  title = "@tool_unpack_text ext4"
  label = "@option_text"
  value-sh = "glog un_tool_ext4 0"
  items = [ "0|imgextractor", "1|imgkit_scuti" ]

  [[action.params]]
  name = "un_tool_erofs"
  title = "@tool_unpack_text erofs"
  label = "@option_text"
  value-sh = "glog un_tool_erofs"
  items = [ "0|extract.erofs", "1|imgkit_scuti" ]

  [[action.params]]
  name = "un_tool_f2fs"
  title = "@tool_unpack_text f2fs"
  label = "@option_text"
  value-sh = "glog un_tool_f2fs 0"
  items = [ "0|extract.f2fs", "1|imgkit_scuti" ]

  [[action.params]]
  name = "re_tool_ext4"
  title = "@tool_repack_text ext4"
  label = "@option_text"
  value-sh = "glog re_tool_ext4 1"
  items = [ "0|make_ext4fs", "1|mke2fs+e2fsdroid", "2|imgkit_scuti" ]

  [[action.params]]
  name = "re_tool_erofs"
  title = "@tool_repack_text erofs"
  label = "@option_text"
  value-sh = "glog re_tool_erofs"
  items = [ "0|mkfs.erofs", "1|imgkit_scuti" ]

  [[action.params]]
  name = "re_tool_f2fs"
  title = "@tool_repack_text f2fs"
  label = "@option_text"
  value-sh = "glog re_tool_f2fs 0"
  items = [ "0|sload_f2fs" ]

[[group]]
[[action]]
title = "@custom_size"
warn = "@custom_size_desc"
icon = "{ICON}/size_icon.png"
shell = "hidden"
reload = true
support = '[ -n "$(ls -1d "$SDH/$PTSH"/* 2>/dev/null | grep -vE "/(raw|config)")" ] && echo 1'
params-sh = '''
for vvsskk in $SDH/$PTSH/*; do
  [[ -d "$vvsskk" ]] && namept="${vvsskk##*/}" || continue
  [[ "$namept" == *config* || "$namept" == *raw* ]] && continue
  cat << EOF
  [[params]]
  name = "name_${namept}"
  type = "number"
  placeholder = "0"
  label = "${namept}"
  value-sh = "cat $SDH/$PTSH/config/${namept}_size.txt 2>/dev/null"
  apply = """
  if [[ -z "\$name_${namept}" || "\$name_${namept}" == 0 ]]; then
    rm -rf $SDH/$PTSH/config/${namept}_size.txt
  else
    echo "\$name_${namept}" > $SDH/$PTSH/config/${namept}_size.txt
  fi
  """
EOF
done
'''
