[[toml]]
load-key = "{HOME}/etc/lang/{LANG}.bash"

[[group]]
[[menu]]
handler = """
if [ "$menu_id" == "v1" ]; then
echo "am:[start -a android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS -d package:com.tool.tree]"
elif [ "$menu_id" == "v2" ]; then
echo "am:[start -a android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION -d package:com.tool.tree]"
elif [ "$menu_id" == "v3" ]; then
echo "am:[start -a android.settings.APPLICATION_DETAILS_SETTINGS -d package:com.tool.tree]"
fi
"""
  
  [[menu.items]]
  key = "v1"
  title = "$permis_text_1"
  silent = true

  [[menu.items]]
  key = "v2"
  title = "$permis_text_4"
  silent = true

  [[menu.items]]
  key = "v3"
  title = "$setting_text_5"
  silent = true

[[group]]
[[text]]
[[text.rows]]
html-file = "{HOME}/etc/html/tool-tree.html"
html-height = 100

[[group]]
[[page]]
title = "$author_text"
icon = "{ICON}/like.png"
html = "https://Kakathic.github.io/Tool-Tree/website/Information.html"

[[group]]
[[page]]
title = "$update_text_5"
icon = "{ICON}/website.png"
html = "https://Kakathic.github.io/Tool-Tree"

[[group]]
[[page]]
title = "Telegram"
icon = "{ICON}/telegram.png"
html = "https://t.me/tooltree"

[[group]]
[[download]]
title = "$download_text stable"
icon = "{ICON}/update.png"
url-sh = "linkgit https://api.github.com/repos/Kakathic/Tool-Tree/releases/latest Tool-Tree"
script = "openfile $state"

[[group]]
[[download]]
title = "$download_text beta"
icon = "{ICON}/update2.png"
url = "https://github.com/Kakathic/Tool-Tree/releases/download/beta/Tool-Tree-beta.apk"
script = "openfile $state"
